python scripts/grid_search.py \
    --base_dir results/ucf_gridsearch_linear \
    --parent_dir data/ucf/grid_search \
    --dataset ucf \
    --model_type mlp \
    --mixup_alpha 0.2 \
    --num_epochs 50 \
    --lr 1e-5 \
    --weight_decay 1e-4 \
    --max_length 300 \
    --decoder_layers 6 \
    --num_partitions 1 \
    --partition_id 0 